#!/bin/sh

# util for using routes collected by vpn-route-fetch

op="${1-add}"

while read route; do
	f="$(echo "$route" | cut -f1 -d',')"
	r="$(echo "$route" | cut -f2 -d',')"

	ip -$f r $op $r

	# if the outgoing interface or the address is removed, the route is removed.
	# to avoid traffic being routed in an undesired way, a blackhole route is
	# created alongside with higher metric.
	metric="$(echo "$r" | sed -En 's/^.*metric +([^ ]+).*$/\1/p')"
	[ -z "$metric" ] && metric=0
	metric="$((metric + 1))"

	for m in via dev src metric from; do
		r="$(echo "$r" | sed -E 's/'"$m"' +([^ ]+)//')"
	done
	ip -$f r $op prohibit $r metric $metric
done
